step0_data-preprocessing:
  p: 32
  h: 32
  chars_per_word: 16
  save_dir: data/
  dataset: snli
  word_vec_save_path: data/word-vectors.npy
step1_trainning:
  batch_size: 70
  eval_interval: 500
  char_embed_size: 8
  char_conv_filters: 100
  char_conv_kernel: 5
  dropout_initial_keep_rate: 1.0
  dropout_decay_rate: 0.977
  dropout_decay_interval: 10000
  l2_full_step: 100000
  l2_full_ratio: 9.0e-05
  l2_diference_penalty: 0.001
  first_scale_down_ratio: 0.3
  transition_scale_down_ratio: 0.5
  growth_rate: 20
  layers_per_dense_block: 8
  dense_blocks: 3
  labels: 3
  load_dir: data
  models_dir: models/
  logdir: logs
  word_vec_path: data/word-vectors.npy
